post  http://localhost:4000/api/users
Content-Type: application/json

{
    "name":"cantarino2",
    "cep": "71995385",
    "document": "sasasa",
    "email": "vc@eu.com",
    "password": "s3nh4!!"    
}



###
PUT http://localhost:4000/api/users/1
Content-Type: application/json

{
    "name":"cantarinoUpdated2"    
}

###
GET http://localhost:4000/api/users/1

###
DELETE  http://localhost:4000/api/users/5